version: "3"

services:
  testdb:
    image: mysql:8.0.17
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test123*
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"

  admin:
    image: adminer
    ports:
      - "8080:8080"
